import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdirSync, rmSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { evaluate } from '../src/hooks/rules-sync.ts';

describe('rules-sync', () => {
  const testDir = join(tmpdir(), 'rules-sync-test');
  const pluginRoot = join(testDir, 'plugin');

  beforeEach(() => {
    mkdirSync(join(testDir, '.ai', 'context'), { recursive: true });
    mkdirSync(join(testDir, '.claude', 'rules'), { recursive: true });
    mkdirSync(join(pluginRoot, 'resources', 'profiles'), { recursive: true });
    process.env['CLAUDE_PROJECT_DIR'] = testDir;
    process.env['CLAUDE_PLUGIN_ROOT'] = pluginRoot;

    // Create template
    writeFileSync(join(pluginRoot, 'resources', 'operating-rules.md'), '# Rules\nRule 1\nRule 2');
  });

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true });
    delete process.env['CLAUDE_PROJECT_DIR'];
    delete process.env['CLAUDE_PLUGIN_ROOT'];
  });

  it('generates rules file from template', () => {
    evaluate({});
    const rulesFile = join(testDir, '.claude', 'rules', 'kronen.md');
    expect(existsSync(rulesFile)).toBe(true);
    const content = readFileSync(rulesFile, 'utf-8');
    expect(content).toContain('Generated by kronen');
    expect(content).toContain('Rule 1');
  });

  it('generates profile cache with defaults when no project.yml', () => {
    evaluate({});
    const cacheFile = join(testDir, '.ai', 'context', 'kronen-profile-cache');
    expect(existsSync(cacheFile)).toBe(true);
    const content = readFileSync(cacheFile, 'utf-8');
    expect(content).toContain('KRONEN_TDD_GATE=enabled');
    expect(content).toContain('KRONEN_TRACING=light');
  });

  it('loads profile from project.yml', () => {
    writeFileSync(join(testDir, '.ai', 'project.yml'), 'profile: personal\n');
    writeFileSync(join(pluginRoot, 'resources', 'profiles', 'personal.yml'), 'tdd_gate: disabled\ntracing: disabled\n');
    evaluate({});
    const content = readFileSync(join(testDir, '.ai', 'context', 'kronen-profile-cache'), 'utf-8');
    expect(content).toContain('KRONEN_TDD_GATE=disabled');
    expect(content).toContain('KRONEN_TRACING=disabled');
  });

  it('refuses to disable safety flags', () => {
    writeFileSync(join(testDir, '.ai', 'project.yml'), [
      'profile: default',
      'overrides:',
      '  hooks:',
      '    scope_guard: disabled',
      '    push_protection: disabled',
    ].join('\n'));
    evaluate({});
    const content = readFileSync(join(testDir, '.ai', 'context', 'kronen-profile-cache'), 'utf-8');
    expect(content).toContain('KRONEN_SCOPE_GUARD=enabled');
    expect(content).toContain('KRONEN_PUSH_PROTECTION=enabled');
  });

  it('skips write when content is unchanged', () => {
    evaluate({});
    const metaFile = join(testDir, '.claude', 'rules', '.kronen-sync-meta');
    const hash1 = readFileSync(metaFile, 'utf-8').trim();
    evaluate({});
    const hash2 = readFileSync(metaFile, 'utf-8').trim();
    expect(hash1).toBe(hash2);
  });

  it('returns warn with profile name', () => {
    const result = evaluate({});
    expect(result.mode).toBe('warn');
    expect(result.message).toContain('synced');
  });
});
