#!/usr/bin/env bash
# test-rules-sync.sh — Unit tests for rules-sync.sh hook
# Run: bash plugins/kronen/scripts/tests/test-rules-sync.sh
# Exit 0 = all pass, Exit 1 = any fail

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HOOK="$SCRIPT_DIR/../rules-sync.sh"
PASS=0
FAIL=0
TOTAL=0
TMPDIR=$(mktemp -d)

# Isolate HOME so tests never touch real ~/.claude/
export HOME="$TMPDIR/fakehome"
mkdir -p "$HOME"

cleanup() { rm -rf "$TMPDIR"; }
trap cleanup EXIT

# --- Test helpers ---

setup_project() {
  local project="$TMPDIR/project-$TOTAL"
  mkdir -p "$project/.ai"
  echo "$project"
}

run_sync() {
  local project_dir="$1"
  local plugin_root="${2:-$SCRIPT_DIR/../..}"
  local exit_code=0
  local output
  output=$(echo '{}' | CLAUDE_PROJECT_DIR="$project_dir" CLAUDE_PLUGIN_ROOT="$plugin_root" bash "$HOOK" 2>&1) || exit_code=$?
  printf '%s' "$output"
  return $exit_code
}

assert_pass() {
  local test_name="$1"
  TOTAL=$((TOTAL + 1))
  printf "  PASS: %s\n" "$test_name"
  PASS=$((PASS + 1))
}

assert_fail() {
  local test_name="$1" reason="$2"
  TOTAL=$((TOTAL + 1))
  printf "  FAIL: %s (%s)\n" "$test_name" "$reason"
  FAIL=$((FAIL + 1))
}

assert_file_exists() {
  local test_name="$1" file="$2"
  TOTAL=$((TOTAL + 1))
  if [ -f "$file" ]; then
    printf "  PASS: %s\n" "$test_name"
    PASS=$((PASS + 1))
  else
    printf "  FAIL: %s (file missing: %s)\n" "$test_name" "$file"
    FAIL=$((FAIL + 1))
  fi
}

assert_file_contains() {
  local test_name="$1" file="$2" pattern="$3"
  TOTAL=$((TOTAL + 1))
  if grep -q "$pattern" "$file" 2>/dev/null; then
    printf "  PASS: %s\n" "$test_name"
    PASS=$((PASS + 1))
  else
    printf "  FAIL: %s (file missing pattern: %s)\n" "$test_name" "$pattern"
    FAIL=$((FAIL + 1))
  fi
}

assert_file_not_contains() {
  local test_name="$1" file="$2" pattern="$3"
  TOTAL=$((TOTAL + 1))
  if ! grep -q "$pattern" "$file" 2>/dev/null; then
    printf "  PASS: %s\n" "$test_name"
    PASS=$((PASS + 1))
  else
    printf "  FAIL: %s (file unexpectedly contains: %s)\n" "$test_name" "$pattern"
    FAIL=$((FAIL + 1))
  fi
}

assert_perms() {
  local test_name="$1" file="$2" expected="$3"
  TOTAL=$((TOTAL + 1))
  local actual
  actual=$(stat -f "%Lp" "$file" 2>/dev/null || stat -c "%a" "$file" 2>/dev/null)
  if [ "$actual" = "$expected" ]; then
    printf "  PASS: %s\n" "$test_name"
    PASS=$((PASS + 1))
  else
    printf "  FAIL: %s (expected %s, got %s)\n" "$test_name" "$expected" "$actual"
    FAIL=$((FAIL + 1))
  fi
}

assert_output_contains() {
  local test_name="$1" output="$2" pattern="$3"
  TOTAL=$((TOTAL + 1))
  if printf '%s' "$output" | grep -q "$pattern"; then
    printf "  PASS: %s\n" "$test_name"
    PASS=$((PASS + 1))
  else
    printf "  FAIL: %s (output missing: %s)\n" "$test_name" "$pattern"
    FAIL=$((FAIL + 1))
  fi
}

# ============================================================
echo "=== rules-sync.sh unit tests ==="
echo ""

# --- Test 1: First install (no .claude/rules/) ---
echo "Test 1: First install"
P=$(setup_project)
output=$(run_sync "$P")
assert_file_exists "rules file created" "$P/.claude/rules/kronen.md"
assert_file_exists "cache file created" "$P/.ai/context/kronen-profile-cache"
assert_file_exists "meta file created" "$P/.claude/rules/.kronen-sync-meta"
assert_file_contains "rules has generated header" "$P/.claude/rules/kronen.md" "Generated by kronen"
echo ""

# --- Test 2: Hash match (no-op fast path) ---
echo "Test 2: Hash match (fast path)"
output=$(run_sync "$P")
if [ -z "$output" ]; then
  assert_pass "no output on hash match"
else
  assert_fail "no output on hash match" "got: $output"
fi
echo ""

# --- Test 3: Hash mismatch (template changed) ---
echo "Test 3: Hash mismatch triggers sync"
echo "stale-hash" > "$P/.claude/rules/.kronen-sync-meta"
output=$(run_sync "$P")
assert_output_contains "sync message on mismatch" "$output" "Kronen rules synced"
echo ""

# --- Test 4: Symlink on target ---
echo "Test 4: Symlink on target"
P=$(setup_project)
mkdir -p "$P/.claude/rules"
ln -sf /tmp/evil "$P/.claude/rules/kronen.md"
output=$(run_sync "$P")
assert_output_contains "symlink warning" "$output" "symlink"
echo ""

# --- Test 5: Symlink on parent directory ---
echo "Test 5: Symlink on parent directory"
P=$(setup_project)
mkdir -p "$P/.claude"
ln -sf /tmp "$P/.claude/rules" 2>/dev/null || true
if [ -L "$P/.claude/rules" ]; then
  output=$(run_sync "$P")
  assert_output_contains "parent symlink warning" "$output" "symlink"
else
  assert_pass "parent symlink warning (could not create symlink — skipped)"
fi
rm -f "$P/.claude/rules" 2>/dev/null
echo ""

# --- Test 6: Path traversal ---
echo "Test 6: Path traversal sanitization"
P=$(setup_project)
cat > "$P/.ai/project.yml" << 'EOF'
profile: "../../etc/passwd"
EOF
output=$(run_sync "$P")
# Should sanitize to "etcpasswd" or warn — either way, no crash
assert_file_exists "still generates rules with defaults" "$P/.claude/rules/kronen.md"
echo ""

# --- Test 7: Malformed project.yml ---
echo "Test 7: Malformed project.yml"
P=$(setup_project)
printf 'not: [valid\nyaml: {{{' > "$P/.ai/project.yml"
output=$(run_sync "$P")
assert_file_exists "still generates rules with defaults" "$P/.claude/rules/kronen.md"
assert_file_contains "defaults to enabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_TDD_GATE=enabled"
echo ""

# --- Test 8: Missing project.yml defaults to all-enabled ---
echo "Test 8: Missing project.yml"
P=$(setup_project)
output=$(run_sync "$P")
assert_file_contains "tdd_gate enabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_TDD_GATE=enabled"
assert_file_contains "tracing light" "$P/.ai/context/kronen-profile-cache" "KRONEN_TRACING=light"
assert_file_contains "verification strict" "$P/.ai/context/kronen-profile-cache" "KRONEN_VERIFICATION=strict"
assert_file_contains "scope_guard enabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_SCOPE_GUARD=enabled"
echo ""

# --- Test 9: Empty template ---
echo "Test 9: Empty template"
P=$(setup_project)
FAKE_PLUGIN="$TMPDIR/fake-plugin"
mkdir -p "$FAKE_PLUGIN/resources/profiles"
cp "$SCRIPT_DIR/../../resources/profiles/"*.yml "$FAKE_PLUGIN/resources/profiles/" 2>/dev/null || true
touch "$FAKE_PLUGIN/resources/operating-rules.md"
output=$(run_sync "$P" "$FAKE_PLUGIN")
# Should still work (empty template is valid, just produces a header-only rules file)
assert_file_exists "rules file created with empty template" "$P/.claude/rules/kronen.md"
echo ""

# --- Test 10: Malformed meta file with shell metacharacters ---
echo "Test 10: Malformed meta file"
P=$(setup_project)
mkdir -p "$P/.claude/rules"
printf '$(rm -rf /); `evil`; $((1+1))\n' > "$P/.claude/rules/.kronen-sync-meta"
output=$(run_sync "$P")
# Should treat as mismatch and rewrite, not execute the content
assert_output_contains "sync on malformed meta" "$output" "Kronen rules synced"
assert_file_not_contains "meta cleaned" "$P/.claude/rules/.kronen-sync-meta" "evil"
echo ""

# --- Test 11: Safety flag override attempt ---
echo "Test 11: Safety flag override rejection"
P=$(setup_project)
cat > "$P/.ai/project.yml" << 'EOF'
profile: work
overrides:
  hooks:
    scope_guard: disabled
    push_protection: disabled
EOF
output=$(run_sync "$P")
assert_output_contains "scope_guard warning" "$output" "Cannot override safety flag"
assert_file_contains "scope_guard forced enabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_SCOPE_GUARD=enabled"
assert_file_contains "push_protection forced enabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_PUSH_PROTECTION=enabled"
echo ""

# --- Test 12: Workflow flag override accepted ---
echo "Test 12: Workflow flag override accepted"
P=$(setup_project)
cat > "$P/.ai/project.yml" << 'EOF'
profile: work
overrides:
  hooks:
    tdd_gate: disabled
    tracing: full
EOF
output=$(run_sync "$P")
assert_file_contains "tdd_gate disabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_TDD_GATE=disabled"
assert_file_contains "tracing full" "$P/.ai/context/kronen-profile-cache" "KRONEN_TRACING=full"
echo ""

# --- Test 13: File permissions ---
echo "Test 13: File permissions"
P=$(setup_project)
run_sync "$P" > /dev/null 2>&1
assert_perms "rules file is 600" "$P/.claude/rules/kronen.md" "600"
assert_perms "cache file is 600" "$P/.ai/context/kronen-profile-cache" "600"
echo ""

# --- Test 14: Dev command validation ---
echo "Test 14: Dev command validation"
P=$(setup_project)
cat > "$P/.ai/project.yml" << 'EOF'
profile: work
dev:
  test: pnpm test
  build: rm -rf / ; evil
  lint: npm run lint
EOF
output=$(run_sync "$P")
assert_file_contains "safe command passes" "$P/.ai/context/kronen-profile-cache" "KRONEN_DEV_TEST=pnpm test"
assert_file_not_contains "unsafe command rejected" "$P/.ai/context/kronen-profile-cache" "evil"
assert_output_contains "unsafe command warning" "$output" "Dev command rejected"
echo ""

# --- Test 15: Personal profile ---
echo "Test 15: Personal profile"
P=$(setup_project)
cat > "$P/.ai/project.yml" << 'EOF'
profile: personal
EOF
output=$(run_sync "$P")
assert_file_contains "tdd_gate disabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_TDD_GATE=disabled"
assert_file_contains "tracing disabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_TRACING=disabled"
assert_file_contains "doc_checkpoint disabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_DOC_CHECKPOINT=disabled"
assert_file_contains "verification light" "$P/.ai/context/kronen-profile-cache" "KRONEN_VERIFICATION=light"
assert_file_contains "scope_guard still enabled" "$P/.ai/context/kronen-profile-cache" "KRONEN_SCOPE_GUARD=enabled"
echo ""

# ============================================================
echo "=== Results ==="
echo "  Total: $TOTAL"
echo "  Pass:  $PASS"
echo "  Fail:  $FAIL"
echo ""

if [ "$FAIL" -gt 0 ]; then
  echo "FAILED"
  exit 1
fi

echo "ALL TESTS PASSED"
exit 0
