import { build } from 'esbuild';
import { existsSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';

const HOOKS_DIR = 'src/hooks';
const CLI_DIR = 'src/cli';
const OUT_DIR = 'dist';

function getEntryPoints(dir) {
  try {
    return readdirSync(dir)
      .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
      .map((f) => join(dir, f));
  } catch {
    return [];
  }
}

// Hooks and CLI wrappers are entry points.
// Utils are pure libraries — they get inlined by whoever imports them.
const entryPoints = [
  ...getEntryPoints(HOOKS_DIR),
  ...getEntryPoints(CLI_DIR),
];

if (entryPoints.length === 0) {
  console.log('No entry points found — skipping build.');
  process.exit(0);
}

// Clean stale output to prevent orphaned files
rmSync(OUT_DIR, { recursive: true, force: true });

await build({
  entryPoints,
  outdir: OUT_DIR,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  minify: false,
  packages: 'bundle',
  banner: {
    js: '// Auto-generated by esbuild — do not edit',
  },
});

// Guard: no chunk splitting should exist — each hook must be self-contained
if (existsSync(join(OUT_DIR, 'chunks'))) {
  console.error('Build error: unexpected chunks directory — splitting may be active');
  process.exit(1);
}

console.log(`Built ${entryPoints.length} self-contained scripts to ${OUT_DIR}/`);
