import { build } from 'esbuild';
import { readdirSync } from 'node:fs';
import { join } from 'node:path';

const HOOKS_DIR = 'src/hooks';
const UTILS_DIR = 'src/utils';
const OUT_DIR = 'dist';

function getEntryPoints(dir) {
  try {
    return readdirSync(dir)
      .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts'))
      .map((f) => join(dir, f));
  } catch {
    return [];
  }
}

const entryPoints = [
  ...getEntryPoints(HOOKS_DIR),
  ...getEntryPoints(UTILS_DIR),
];

if (entryPoints.length === 0) {
  console.log('No entry points found — skipping build.');
  process.exit(0);
}

await build({
  entryPoints,
  outdir: OUT_DIR,
  bundle: true,
  splitting: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: false,
  minify: false,
  packages: 'bundle',
  banner: {
    js: '// Auto-generated by esbuild — do not edit',
  },
  chunkNames: 'chunks/[name]-[hash]',
});

console.log(`Built ${entryPoints.length} scripts to ${OUT_DIR}/`);
