import { createRunner, projectPath, pluginPath, parseYamlFile } from '@kronen/hook-utils';
import type { HookInput, HookResult } from '@kronen/hook-utils';
import { existsSync, readFileSync, writeFileSync, mkdirSync, renameSync, unlinkSync, lstatSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname } from 'node:path';

const SAFETY_FLAGS = new Set(['scope_guard', 'push_protection']);
const SAFE_COMMAND_PATTERN = /^[a-zA-Z0-9_./ -]+$/;

const DEFAULT_FLAGS: Record<string, string> = {
  tdd_gate: 'enabled',
  tracing: 'light',
  doc_checkpoint: 'enabled',
  verification: 'strict',
  scope_guard: 'enabled',
  push_protection: 'enabled',
};

/**
 * SessionStart hook: syncs plugin operating rules and profile config.
 * Reads .ai/project.yml, resolves profile, applies overrides, compiles cache,
 * generates .claude/rules/kronen.md. Uses content hashing to skip unchanged writes.
 */
export function evaluate(_input: HookInput): HookResult {
  const templatePath = pluginPath('resources', 'operating-rules.md');
  if (!existsSync(templatePath)) {
    return { mode: 'warn', message: 'Kronen rules sync: template not found — skipping' };
  }

  const template = readFileSync(templatePath, 'utf-8');
  const flags = resolveFlags();
  const devCommands = resolveDevCommands();

  const rulesContent = `<!-- Generated by kronen. Do not edit manually. Changes will be overwritten by rules-sync.sh -->\n${template}`;
  const cacheContent = buildCacheContent(flags, devCommands);

  // Content hash comparison
  const newHash = createHash('sha256').update(rulesContent + '\n' + cacheContent).digest('hex');
  const metaFile = projectPath('.claude', 'rules', '.kronen-sync-meta');

  if (existsSync(metaFile)) {
    const oldHash = readFileSync(metaFile, 'utf-8').trim();
    if (/^[a-f0-9]{64}$/.test(oldHash) && newHash === oldHash) {
      return { mode: 'warn', message: `Kronen rules synced (profile: ${flags.profileName})` };
    }
  }

  // Write files atomically
  const rulesFile = projectPath('.claude', 'rules', 'kronen.md');
  if (isSymlink(rulesFile)) {
    return { mode: 'warn', message: 'Kronen rules sync: rules file is a symlink — skipping' };
  }

  atomicWrite(rulesFile, rulesContent);
  atomicWrite(projectPath('.ai', 'context', 'kronen-profile-cache'), cacheContent);
  atomicWrite(metaFile, newHash);

  return { mode: 'warn', message: `Kronen rules synced (profile: ${flags.profileName})` };
}

interface ResolvedFlags {
  profileName: string;
  values: Record<string, string>;
}

function resolveFlags(): ResolvedFlags {
  const values = { ...DEFAULT_FLAGS };
  let profileName = 'default';

  const configPath = projectPath('.ai', 'project.yml');
  if (!existsSync(configPath)) {
    return { profileName, values };
  }

  const config = parseYamlFile<Record<string, unknown>>(configPath);
  if (!config) return { profileName, values };

  // Load profile
  if (typeof config.profile === 'string') {
    profileName = config.profile.replace(/[^a-zA-Z0-9_-]/g, '');
    const profileFile = pluginPath('resources', 'profiles', `${profileName}.yml`);
    if (existsSync(profileFile)) {
      const profile = parseYamlFile<Record<string, string>>(profileFile);
      if (profile) {
        for (const key of Object.keys(DEFAULT_FLAGS)) {
          if (typeof profile[key] === 'string') values[key] = profile[key];
        }
      }
    }
  }

  // Apply overrides
  const overrides = config.overrides as Record<string, unknown> | undefined;
  const hookOverrides = overrides?.hooks as Record<string, string> | undefined;
  if (hookOverrides) {
    for (const [key, val] of Object.entries(hookOverrides)) {
      if (typeof val !== 'string') continue;
      if (SAFETY_FLAGS.has(key) && val !== 'enabled') continue; // Cannot disable safety flags
      if (key in values) values[key] = val;
    }
  }

  // Force safety flags (defense in depth)
  values.scope_guard = 'enabled';
  values.push_protection = 'enabled';

  return { profileName, values };
}

function resolveDevCommands(): Record<string, string> {
  const configPath = projectPath('.ai', 'project.yml');
  if (!existsSync(configPath)) return {};

  const config = parseYamlFile<Record<string, unknown>>(configPath);
  const dev = config?.dev as Record<string, string> | undefined;
  if (!dev) return {};

  const result: Record<string, string> = {};
  for (const key of ['test', 'build', 'lint']) {
    const cmd = dev[key];
    if (typeof cmd === 'string' && SAFE_COMMAND_PATTERN.test(cmd)) {
      result[key] = cmd;
    }
  }
  return result;
}

function buildCacheContent(flags: ResolvedFlags, devCommands: Record<string, string>): string {
  const lines = [
    '# kronen-profile-cache (auto-generated by rules-sync — do not edit)',
    ...Object.entries(flags.values).map(([k, v]) => `KRONEN_${k.toUpperCase()}=${v}`),
    `KRONEN_DEV_TEST=${devCommands.test ?? ''}`,
    `KRONEN_DEV_BUILD=${devCommands.build ?? ''}`,
    `KRONEN_DEV_LINT=${devCommands.lint ?? ''}`,
  ];
  return lines.join('\n');
}

function isSymlink(path: string): boolean {
  try {
    return lstatSync(path).isSymbolicLink();
  } catch {
    return false;
  }
}

function atomicWrite(target: string, content: string): void {
  const dir = dirname(target);
  if (isSymlink(dir)) return;

  mkdirSync(dir, { recursive: true });
  const tmpFile = `${target}.tmp.${process.pid}`;
  writeFileSync(tmpFile, content + '\n', { mode: 0o600 });
  renameSync(tmpFile, target);

  // Post-write symlink check
  if (isSymlink(target)) {
    try { unlinkSync(target); } catch { /* ignore */ }
  }
}

if (!process.env['VITEST']) {
  const run = createRunner(evaluate);
  await run();
}
