#!/usr/bin/env bash
# claude-core — PreCompact hook: capture working state before context compression
# Writes .ai/compact-snapshot.yml for session-recovery to consume on resume.
# PreCompact has no stdin, cannot block. Always exits 0.

set -euo pipefail

main() {
  PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
  SNAPSHOT="$PROJECT_DIR/.ai/compact-snapshot.yml"
  TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)

  # --- Active plan state ---
  PLAN_NAME=""
  PLAN_WAVE=""
  PLAN_TASK=""
  ERROR_COUNT=0

  for state_file in "$PROJECT_DIR"/.ai/plans/*/state.yml; do
    [ ! -f "$state_file" ] && continue
    local status_line=""
    status_line=$(grep '^status:' "$state_file" | head -1) || true
    status_line="${status_line#status: }"; status_line="${status_line//\"/}"

    if [ "$status_line" = "in_progress" ]; then
      PLAN_NAME=$(grep '^plan:' "$state_file" | head -1) || true
      PLAN_NAME="${PLAN_NAME#plan: }"; PLAN_NAME="${PLAN_NAME//\"/}"
      PLAN_WAVE=$(grep '^current_wave:' "$state_file" | head -1) || true
      PLAN_WAVE="${PLAN_WAVE#current_wave: }"; PLAN_WAVE="${PLAN_WAVE//\"/}"
      PLAN_TASK=$(grep '^current_task:' "$state_file" | head -1) || true
      PLAN_TASK="${PLAN_TASK#current_task: }"; PLAN_TASK="${PLAN_TASK//\"/}"
      ERROR_COUNT=$(grep -c '  - timestamp:' "$state_file" 2>/dev/null) || ERROR_COUNT=0
      break
    fi
  done

  # --- Active project from agency.yml ---
  ACTIVE_PROJECT=""
  AGENCY_FILE="$PROJECT_DIR/.ai/agency.yml"
  if [ -f "$AGENCY_FILE" ]; then
    ACTIVE_PROJECT=$(grep '^active:' "$AGENCY_FILE" | head -1) || true
    ACTIVE_PROJECT="${ACTIVE_PROJECT#active: }"; ACTIVE_PROJECT="${ACTIVE_PROJECT//\"/}"
  fi

  # --- Modified files from trace-light.log ---
  MODIFIED_FILES=()
  TRACE_FILE="$PROJECT_DIR/.ai/traces/trace-light.log"
  if [ -f "$TRACE_FILE" ]; then
    while IFS= read -r line; do
      # Extract tool name (field 2)
      local rest="${line#*|}"
      local tool="${rest%%|*}"
      case "$tool" in
        Write|Edit)
          # Context is always the last field — handles both 4-field and 5-field formats
          local context="${line##*|}"
          [ -n "$context" ] && [ "$context" != "-" ] && MODIFIED_FILES+=("$context") ;;
      esac
    done < <(tail -20 "$TRACE_FILE")

    # Deduplicate (bash 3 compatible — no associative arrays)
    if [ ${#MODIFIED_FILES[@]} -gt 0 ]; then
      local unique=()
      local seen=""
      for f in "${MODIFIED_FILES[@]}"; do
        case "$seen" in
          *"|$f|"*) ;;
          *) seen="${seen}|$f|"; unique+=("$f") ;;
        esac
      done
      MODIFIED_FILES=("${unique[@]}")
    fi
  fi

  # --- Write snapshot ---
  {
    echo "# Auto-generated by PreCompact hook — consumed by SessionStart, then deleted"
    echo "generated: \"$TS\""

    if [ -n "$PLAN_NAME" ]; then
      echo "active_plan:"
      echo "  name: \"$PLAN_NAME\""
      echo "  wave: \"$PLAN_WAVE\""
      echo "  task: \"$PLAN_TASK\""
    else
      echo "active_plan: null"
    fi

    if [ -n "$ACTIVE_PROJECT" ]; then
      echo "active_project: \"$ACTIVE_PROJECT\""
    else
      echo "active_project: null"
    fi

    if [ ${#MODIFIED_FILES[@]} -gt 0 ]; then
      echo "modified_files:"
      for f in "${MODIFIED_FILES[@]}"; do
        echo "  - $f"
      done
    else
      echo "modified_files: []"
    fi

    echo "error_count: $ERROR_COUNT"
  } > "$SNAPSHOT"
}

# Trap errors — always exit 0
trap 'exit 0' ERR
main
exit 0
